### ISSUE TITLE
Adding nvidia-open-dkms in driver packages

### ISSUE THREAD

**Issue by cblinq** [korvahannu/arch-nvidia-drivers-installation-guide#30]
Hi, could you kindly also add the option of nvidia-open-dkms in the driver packages table?

https://wiki.archlinux.org/title/NVIDIA Here is the official Arch wiki.

**Comment by korvahannu** [comment]
Done!

**Comment by cblinq** [comment]
@korvahannu Thank you, I see that you forgot to add -dkms for the non-linux kernels.

**Comment by korvahannu** [comment]
@cblinq Whoops! Fixed 😆
